---

- name: Ensure epel-release is installed.
  package:
    name: epel-release
    state: present

- name: Ensure nginx is installed.
  package:
    name: nginx
    state: present

- name: Ensure PIP package-manager is installed.
  package:
    name: python-pip
    state: latest

- name: install latest pyOpenSSL module if needed
  pip:
    name: pyOpenSSL
    state: latest
