# -*- mode: ruby -*-
# vim: set ft=ruby :

$bootstrap = <<SCRIPT
yum install epel-release.noarch -y
yum install wget vim -y
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io -y
systemctl enable docker
systemctl start docker && sleep 5
docker swarm init --advertise-addr 10.143.65.13
SCRIPT
# mkdir ansible && mkdir pip && mkdir python3

$ssh_auth = <<SCRIPT
ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""
ssh-keygen -t rsa -f /home/vagrant/.ssh/id_rsa -q -P ""
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.define "docker-host" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname="docker-host"
    subconfig.vm.network "forwarded_port", guest: 443, host: 443
    subconfig.vm.network :private_network, ip: "10.143.65.13"
    subconfig.vm.provision "shell", inline: $ssh_auth
    subconfig.vm.provision "shell", inline: $bootstrap
	  config.ssh.forward_agent = true
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
    end
  end

end
