# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "wordpress" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname="wordpress"
    subconfig.vm.network "forwarded_port", guest: 443, host: 443
    subconfig.vm.network :private_network, ip: "192.168.0.13"
    subconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordpress.yaml"
    end
	  config.ssh.forward_agent = true
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "mysql" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname="mysql"
    subconfig.vm.network :private_network, ip: "192.168.0.14"
    subconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordpress.yaml"
    end
	  config.ssh.forward_agent = true
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

end
